framework: jest
preRun:
     command:
        - yarn install
postMerge:
  pattern: 
    - "./test/**/*.test.ts"
preMerge:
  pattern:
    - "./test/**/*.test.ts"
postRun:
     command:
        - yarn --version
version: 1.0

