framework: jest
preRun:
     command:
        - yarn install
postMerge:
  pattern: 
    - "./test/unit/*.ts"

preMerge:
  pattern:
    - "./test/unit/utils-safePackageName.test.ts"
postRun:
     command:
        - yarn --version
version: 1.0

